import scrapy
from scrapy.http import FormRequest, Request



class VolunteerFairfax(scrapy.Spider):

	name = 'fairfax'
	start_urls = ['http://volunteerfairfax.civicore.com/public/index.php?section=volunteersForChange&action=needToLogin']

	def parse(self,response):

		return scrapy.FormRequest.from_response(
			response,
			clickdata = '//*[@id="ajaxAutoGeneratedID_1000016"]',
			formdata={'Email address': 'volunteerfairfax1@gmail.com','Password': 'farside123'},
			dont_click = True,
			callback=self.after_login)

	def after_login(self,response):

		for i in range(8,11):

			url = 'http://volunteerfairfax.civicore.com/index.php?section=organizations&action=view&fwID=8' + str(i)

			yield scrapy.Request(url,callback = self.parse_item)

	def parse_item(self,response):

		npo_name = (response.xpath('//*[@id="form__ajaxAutoGeneratedID_1000224__field__1_0_organizationName"]/table/tbody/tr/td/text()').extract_first())
		mailing_address = (response.xpath('//*[@id="form__ajaxAutoGeneratedID_1000224__field__1_0_mailingAddress1"]/table/tbody/tr/td/text()').extract_first()).strip()
		mailing_city = (response.xpath('//*[@id="form__ajaxAutoGeneratedID_1000224__field__1_0_mailingCity"]/table/tbody/tr/td/text()').extract_first()).strip()
		mailing_state = (response.xpath('//*[@id="form__ajaxAutoGeneratedID_1000224__field__1_0_mailingState"]/table/tbody/tr/td/text()').extract_first()).strip()
		mailing_zipcode = (response.xpath('//*[@id="form__ajaxAutoGeneratedID_1000224__field__1_0_mailingZipCode"]/table/tbody/tr/td/text()').extract_first()).strip()
		phone_num = (response.xpath('//*[@id="form__ajaxAutoGeneratedID_1000224__field__1_0_phone1"]/table/tbody/tr/td/text()').extract_first()).strip()
		causes_list = response.xpath('//*[@id="form__ajaxAutoGeneratedID_1001069__field__1_0_missionType"]/table/tbody/tr/td/text()').extract()
		clean_data_causes = []
		mission_statement = (response.xpath('//*[@id="form__ajaxAutoGeneratedID_1001069__field__1_0_missionStatement"]/table/tbody/tr/td/text()').extract_first()).strip()

		for cause in causes_list:

			cause = cause.strip()
			clean_data_causes.append(cause)

		yield {

		'NPO name': npo_name,
		'Address': [mailing_address,mailing_city,mailing_state,mailing_zipcode],
		'Phone number': phone_num,
		'Website': response.xpath('//*[@id="form__ajaxAutoGeneratedID_1000224__field__1_0_website"]/table/tbody/tr/td/a/@href').extract_first(),
		'Causes': clean_data_causes,
		'Email': "",
		'Mission Statement': mission_statement,
		'POC': "",
		'POC Title': "",
		'Twitter': "",
		'Facebook': ""

		}

